### ISSUE TITLE
localised language name should default to native name if localisation not known

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#16]
This seems to work for some languages, but not others.  In the attached screenshot, it works for `bak`, `kum`, `chv`, `tur`, but not `nog`, `sah`, `tyv`, `uig`, despite all being in apertium-apy's database (as of [r61517](https://sourceforge.net/p/apertium/svn/61517/)).  This may be a bug in [apertium-apy](http://wiki.apertium.org/wiki/Apertium-apy), but requires investigation either way.

![screenshot_2015-08-20_220548](https://cloud.githubusercontent.com/assets/963849/9399846/104e85c4-4788-11e5-99e5-95c337f57651.png)

**Comment by sushain97** [comment]
This behavior is by design.

Apertium APY's database is not used for this localization since it would require too many requests.

Instead, the native names are hardcoded in https://github.com/goavki/apertium-html-tools/blob/master/assets/js/localization.js#L2. The languages you mention need to be added to it.

**Comment by jonorthwash** [comment]
Oh, it doesn't get them from the database that apy uses?

**Comment by sushain97** [comment]
No, it doesn't. That would require one request per target language.

**Comment by jonorthwash** [comment]
Oof, I see.  Okay, I'll add that then! :D
