### ISSUE TITLE
AJAX call in localizeStrings() and getLocales() method erroneusly displays Installation Notification 

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#190]
The AJAX call made in the `localizeStrings()` and `getLocales()` method does not get invoked through `callApy` as a result of which `apyRequestStartTime` is not re-assigned ie. its value is same as the start time of a previously executed AJAX request invoked through callApy. The difference between `Date.now()` and `apyRequestStartTime` thus, exceeds individual duration thereby erroneusly displaying the notification.

The last value '11084' in the console corresponds to the value = `Date.now() - apyRequestStartTime`.

![screenshot from 2017-08-19 01-24-08](https://user-images.githubusercontent.com/8894636/29475499-a2d6e4de-847d-11e7-870b-05aee4a4633f.png)

**Comment by share-with-me** [comment]
@sushain97 , Would an appropriate fix for this be invoking those AJAX calls through `callApy`?

**Comment by sushain97** [comment]
If that’s a clean fix (i.e. relatively small change), it sounds good.

**Comment by sushain97** [comment]
I took another look at this and `localizeStrings` doesn't even go through APy. The proper solution for this is setting `apyRequestStartTime = undefined` and then not running `handleAPyRequestCompletion` if `!apyRequestStartTime`. Then we won't have this problem with any other random AJAX calls we do.

Considering this bug as relatively high priority since it has the potential to be really annoying for a user.
