### ISSUE TITLE
Clicking on Translate Button when on sm-* or xs-* screen width does not call translate()

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#192]
The `translate` button for interface corresponding to the `xs-*` sized screen does not have the `id='translate'` and thus, clicking on it does not call the `translate()` method.

**Comment by sushain97** [comment]
This must have worked at some point. It could never have had the right id
since they're unique per page. We should really have regression tests...

On Aug 19, 2017 3:24 PM, "Monish Godhia" <notifications@github.com> wrote:

The translate button for interface corresponding to the xs-* sized screen
does not have the id='translate' and thus, clicking on it does not call the
translate() method.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/issues/192>, or mute the
thread

**Comment by share-with-me** [comment]
Would it make sense to use `.translateBtn` class as it is common across the buttons on both screen sizes? Please see #193

**Comment by sushain97** [comment]
If it's not used anywhere else, yes. When did this regression occur?

**Comment by share-with-me** [comment]
> If it's not used anywhere else, yes

This class is only used twice corresponding to the two occurrences of `translate` button. Thus, it is used at no other place except the `translate` button.

> When did this regression occur?

Um, regression as in this bug? I am not sure. I do not recollect removing an id for an existing element. How can one find out?

**Comment by share-with-me** [comment]
I believe an analogous fix would also be required for `detectLanguage` button.

**Comment by sushain97** [comment]
You could try git bisect. Looking at the blame might also be a simple route.

**Comment by sushain97** [comment]
Looks like it's been broken for a while so I wouldn't worry about figuring
out when.
