### ISSUE TITLE
Use a JSON config file instead of a config.conf file.

### ISSUE THREAD

**Issue by svineet** [goavki/apertium-html-tools#36]
Easier to parse for both JavaScript and Python, and avoids the processing we need to do to convert into JSON from ConfigParser syntax.

**Comment by unhammer** [comment]
is the config.conf parsed from js? (what if we want something like a secret key in a future version of the config?)

**Comment by svineet** [comment]
No, during the `make` process we convert config.conf from python's ConfigParser syntax to JSON and then store it as JSON to `build/assets/js/config.js`. I don't understand why we need python as an intermediate, I think we should consider using a config.json file instead, avoiding the extra processing in `read-conf.py`.

About secret keys, IMHO it would be bad design to use anything like a secret key on the frontend since the frontend code can easily be viewed by the user. So yeah secrets can't be secret i.e everything involving a secret key should be done server side.

**Comment by unhammer** [comment]
The config.conf can't be read by the user since it's in a parent folder, but OTOH I can't think of any good reason currently to have secrets for the frontend build.

If having a JSON config makes the code simpler all round it's probably a Good Thing, but I'm not quite convinced it will: Any replacement for `read-conf.py` would also have to be able to query the json during build (see the Makefile), and do the validation (see  `def check_config`) and insert default/fallback values (see `def load_conf`). The actual js-producing part of `read-conf.py` is a single line, while the conf-reading part is three (including `with open(filename…)`). The rest is validation, checking, querying.

**Comment by svineet** [comment]
good point, should I close this?
