### ISSUE TITLE
414: Request-URI too large (should use POST?)

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#79]
I tried translating the text of http://www.elespanol.com/ciencia/tecnologia/20160926/158484429_0.html and got "Translation not yet available!", console showed the request was sent as GET and got back a 414.

**Comment by VictorVelev** [comment]
I want to fix it!

**Comment by share-with-me** [comment]
@unhammer , @sushain97 , I have changed the GET method to POST method in translateText() function and it now processess  the bigger amount of data and does not give '414 error'. (SS below) However, I had a few questions:
1. $.jsonp does not work with any method except 'GET'. This is the link to support this argument. [Stackoverflow](http://stackoverflow.com/questions/4508198/how-to-use-type-post-in-jsonp-ajax-call)
2. Now, if we want to use 'POST' to cater to bigger amount of text, we will have to switch to some other method - which is what I have used ($.ajax())
3. I read in the uses of jsonp datatype that it allows transfer of data between domains of different origins. Now, will that be restricted if I use $.ajax() instead of that? Also, does this expose any security threat for the application? Thanks!
I uses some data from the above mentioned website and tested it with GET and POST. Below are screenshots!
![get_query](https://cloud.githubusercontent.com/assets/8894636/23831066/6c85af66-073f-11e7-9714-2aab2780d7ce.png)
![post_query](https://cloud.githubusercontent.com/assets/8894636/23831068/73524c32-073f-11e7-902f-c2a1c2a4d205.png)

**Comment by share-with-me** [comment]
Should we keep an upper limit on the length of input text box and put a feature like overflow-y: scroll? Currently, the size of text box shows no limit and dynamically updates its size with data?

**Comment by sushain97** [comment]
@share-with-me There's no need for a `y-overflow: scroll`. However, I just added #108 which may mitigate the problem you mention.

**Comment by sushain97** [comment]
@share-with-me There's no security threat. However, the limitation you discuss is valid. Great research.

I would suggest that you use POST (btw `$.post` exists) when a 414 would happen (this requires some research) and JSONP otherwise. POST won't work due to cross-domain restrictions for some installations so we don't want to use it by default, only when necessary.

**Comment by share-with-me** [comment]
@sushain97 Sure! I will try this with $.post() too! Thank you for all the information :D . As for task #108, I will get on it. What is bugging me since evening is the right-to-left-ish behaviour of data when cookies are disabled :P

**Comment by unhammer** [comment]
In particular, JSONP is required when the server isn't sending the [CORS](https://enable-cors.org/) header – but shouldn't APY always be sending that? (Apy doesn't yet have any features which handle sensitive data that I can think of.)

**Comment by share-with-me** [comment]
As per the CORS website, if we setup the CORS on the server with specifying which methods to allow, we achieve the functionality of JSONP. Is my understanding correct in this direction? APY would need this as requests could be cross domain!

**Comment by share-with-me** [comment]
I just tried the JSONP method with $.post() instead of $.ajax(), and I get the error of 501 - Unsupported Method. On googling, it says I need to allow access options on python server. Does this have something to do what CORS is trying to enable? Why can't we just use $.ajax() with a type: 'POST' (which works fine) instead of $.post() which raises the above issue?

**Comment by unhammer** [comment]
https://github.com/goavki/apertium-apy/blob/master/servlet.py#L242 are the lines that set the CORS headers in apy (so if regular /translate calls etc. don't work cross-origin with APY, then that's a bug in apy).

**Comment by unhammer** [comment]
But APY might not have POST methods, just GET methods ;-) that would be a different issue from cors-support

**Comment by share-with-me** [comment]
APY could use POST method when the data is too big right? In which case, CORS will come handy!

**Comment by share-with-me** [comment]
If handler has taken care of 'GET, PUT, POST' options in the servlet.py, why do I get the error of unsupported method - 501 on using $.post(). Is this a bug? Or am I going wrong about this?

**Comment by unhammer** [comment]
APY is the server https://github.com/goavki/apertium-apy/ 
On looking over the code, it seems we do `def post(self): self.get()` in BaseHandler, so every get request should also be possible through post.

I had to re-read the comments to understand the issue – jsonp not working with POST is [to](http://www.markhneedham.com/blog/2009/08/27/jquery-post-jsonp-and-cross-domain-requests/) [be](http://stackoverflow.com/a/4508215/69663) [expected](http://stackoverflow.com/a/2699351/69663). I don't think any fancy hacks around that are worth it – if a browser is old enough to not support CORS, they'll just have to translate less text at a time ;)

**Comment by share-with-me** [comment]
@unhammer Ohh! now I get what APY is. Awesome! However, We face two scenarios. If we use a method like $.ajax() with 'POST' to transfer the text to the server, we overcome the issue 414 but we lose the flexibility of cross domain data transfer. If we stick toy $.jsonp(), we achieve the cross browser domain functionality but we will encounter 414 for large amounts of data. So what should we do? Stick to the latter to change to the former. (If we stick to first, we will surely get 414 which is what issue is asking to solve!)

**Comment by share-with-me** [comment]
Also, if the APY server handler has been defined to use 'GET, PUT, POST' functions, why do I get the error 501- Unsupported method when I use $.post() method?
![screen shot 2017-03-13 at 2 50 39 pm](https://cloud.githubusercontent.com/assets/8894636/23848294/89a9928e-07fc-11e7-9a7c-03113996a90d.png)

**Comment by unhammer** [comment]
No, because APY sends the CORS header, POST should work cross-domain too.

 POST can't work with jsonp (jsonp is a hack around the lack of CORS – https://en.wikipedia.org/wiki/JSONP is interesting reading).

What we should ideally do is just use GET for small requests, POST for large ones. We can use jsonp for the GET requests (would let the old/buggy browsers at least make short requests, though not longer ones).

**Comment by share-with-me** [comment]
The article is very informative. @unhammer , so should I go ahead and make a PR by using $.ajax() with 'POST' as it can handle large texts and cross domains too?

**Comment by unhammer** [comment]
yes

**Comment by share-with-me** [comment]
@unhammer  Created a PR but currently only focusing on translate mode. I will update them across other modes too if and when needed and after getting accustomed to understanding what other modes do.

**Comment by share-with-me** [comment]
Will add the functionality to all the AJAX calls accompanied with `GET` method, as each of them would fail in case of query size being greater than 2048.

**Comment by sushain97** [comment]
fixed with d40162f4c134c2b168d7f28627606d3ac7c58630
