### ISSUE TITLE
meta description not localised?

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#98]
```
$ curl -Ss https://www.apertium.org/index.spa.html|grep '"description"'
        <meta name="description"  data-textattr="content" data-text="description" content="Apertium is a rule-based machine translation platform. It is free software and released under the terms of the GNU General Public License.">
```

etc. for nno, nob, cat – all in English

**Comment by sushain97** [comment]
Hm, the problem is that nno, nob and cat are missing "description". e.g. in `nno.json`:

```json
"missing": [
    "Mark_Unknown_Words",
    "Multi_Step_Translation",
    "description"
]
```

`arg.json` is not and therefore it works fine:

```html
<meta name="description"  data-textattr="content" data-text="description" content="Apertium ye una plataforma de traducción automatica basada en relgas. Ye software libre y se publica baixo os termins d'a GNU General Public License">
```

**Comment by share-with-me** [comment]
@sushain97 A lot of localised webpages still do not have their meta description localised. I checked 'index.fra.html' and others too. How should we update / find the relevant information for 'missing' key for these 'locale.json' files? Can't we use apertium translate and update the info? (Like in 'arg.json')? If yes, I would like to finish up this task!

**Comment by sushain97** [comment]
@share-with-me This is correct, there are many that don't!

Unfortunately, the best way to fix them is by waiting for someone who knows the language to contribute. Feel free to contribute to any of the `*.json` that you speak! :)

It would be cool to leverage Apertium to translate these. I'm opening a new issue (#109) on it since it would be a larger effort (perhaps a bit too big for a coding challenge but it is up to you of course).

**Comment by share-with-me** [comment]
@sushain97  Sure! I speak Hindi and I will try to add this new language to the apertium collection! :D
